package app.aaps.core.interfaces.aps

import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.Serializable

@OptIn(InternalSerializationApi::class)
@Serializable
data class OapsProfileDynamic(
    var dia: Double, // AMA only
    var min_5m_carbimpact: Double, // AMA only
    var max_iob: Double,
    var max_daily_basal: Double,
    var max_basal: Double,
    var min_bg: Double,
    var max_bg: Double,
    var target_bg: Double,
//    var carb_ratio: Double,
    var sens: Double,
    var autosens_adjust_targets: Boolean, // AMA only
//    var max_daily_safety_multiplier: Double,
//    var current_basal_safety_multiplier: Double,
//    var high_temptarget_raises_sensitivity: Boolean,
//    var low_temptarget_lowers_sensitivity: Boolean,
//    var sensitivity_raises_target: Boolean,
//    var resistance_lowers_target: Boolean,
    var adv_target_adjustments: Boolean,
    var exercise_mode: Boolean,
    var half_basal_exercise_target: Int,
//    var maxCOB: Int,
    var skip_neutral_temps: Boolean,
    var remainingCarbsCap: Int,
//    var enableUAM: Boolean,
    var A52_risk_enable: Boolean,
    var SMBInterval: Int,
//    var enableSMB_with_COB: Boolean,
//    var enableSMB_with_temptarget: Boolean,
//    var allowSMB_with_high_temptarget: Boolean,
//    var enableSMB_always: Boolean,
//    var enableSMB_after_carbs: Boolean,
    var maxSMBBasalMinutes: Int,
    var maxUAMSMBBasalMinutes: Int,
    var bolus_increment: Double,
//    var carbsReqThreshold: Int,
    var current_basal: Double,
    var temptargetSet: Boolean,
    var autosens_max: Double,
    var out_units: String,
    var lgsThreshold: Int?,
    //DynISF only
    var variable_sens: Double,
    var insulinDivisor: Int,
    var TDD: Double,

    //eigen
    var BolusBoostSterkte: Int,
    var BolusBoostDeltaT: Int,
    var PersistentDagDrempel: Double,
    var PersistentNachtDrempel: Double,
    var PersistentGrens: Double,
    var bg_PercOchtend: Int,
    var bg_PercMiddag: Int,
    var bg_PercAvond: Int,
    var bg_PercNacht: Int,
    var BoostPerc: Int,
    var maxBoostPerc: Int,
    var Stappen: Boolean,
    var newuamboostDrempel: Double,
    var newuamboostPerc: Int,
    var hypoPerc: Int,
    var BgIOBPerc: Int,
    var standaardTDD: Double,
    var basaalTDDPerc: Int,
    var TDDweegfactor: Int,
    var minbasaal: Double,
    var maxbasaal: Double,
    var dynBasaal: Double,
    var gemTDD: Double,
    var TDDLog: String,
    var dynISFperc: Int,
    var dynISF: Double,
    var resistentie_log: String,
    var resistentie: Boolean,
    var minResistentiePerc: Int,
    var maxResistentiePerc: Int,
    var dagResistentiePerc: Int,
    var nachtResistentiePerc: Int,
    var ResistentieDagen: Int,
    var ResistentieUren: Int,
    var SMBversterkerPerc: Int,
    var SMBversterkerWachttijd: Int,
    var stapactiviteteitPerc: Int,
    var stap5minuten: Int,
    var stapretentie: Int,
    var LKhbooststerkte: Int,
    var LKhboostsmb: Double,
    var MKhbooststerkte: Int,
    var MKhboostsmb: Double,
    var HKhbooststerkte: Int,
    var HKhboostsmb: Double,
    var Bstbooststerkte: Int,
    var OchtendStart: String,
    var MiddagStart: String,
    var AvondStart: String,
    var NachtStart: String,
)